import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/tanstack-provider";
import TheHeader from "@/components/header/TheHeader";
import { CartProvider } from "@/context/cartContext";
import { Toaster } from "@/components/ui/toaster";
import TheAnnouncement from "@/components/announcement/TheAnnouncement";
import TheFooter from "@/components/footer/TheFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <CartProvider>
            <TheAnnouncement />
            <TheHeader />
            {children}
            <TheFooter />
            <Toaster />
          </CartProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
